/*
 * Copyright (C) 2014-2014 Wiky L(wiiiky@yeah.net)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * this file is generated by gobj(https://github.com/wiiiky/gobj)
 */

#include "wlbterproperties.h"

enum {
    PROPERTY_TORRENT=1,
};

G_DEFINE_TYPE(WlBterProperties, wl_bter_properties, GTK_TYPE_DIALOG);

static void wl_bter_properties_init(WlBterProperties *obj);
static void wl_bter_properties_finalize(GObject *obj);
static void wl_bter_properties_class_init(WlBterPropertiesClass *klass);
static void wl_bter_properties_getter(GObject *object,guint property_id,
                                      GValue *value,GParamSpec *ps);
static void wl_bter_properties_setter(GObject *object,guint property_id,
                                      const GValue *value,GParamSpec *ps);

static void wl_bter_properties_init(WlBterProperties *obj)
{
    gtk_dialog_add_button (GTK_DIALOG(obj),"Close",GTK_RESPONSE_CLOSE);

    obj->torrent=NULL;
}

static void wl_bter_properties_finalize(GObject *obj)
{
}

static void wl_bter_properties_class_init(WlBterPropertiesClass *klass)
{
    GObjectClass *objClass=G_OBJECT_CLASS(klass);
    objClass->get_property=wl_bter_properties_getter;
    objClass->set_property=wl_bter_properties_setter;
    objClass->finalize=wl_bter_properties_finalize;

    GParamSpec *ps;
    /* properties */
    ps=g_param_spec_pointer ("torrent",
                             "tr_torrent",
                             "Tr Torrent",
                             G_PARAM_READABLE|G_PARAM_WRITABLE|
                             G_PARAM_CONSTRUCT_ONLY);
    g_object_class_install_property (objClass,PROPERTY_TORRENT,ps);
}

static void wl_bter_properties_getter(GObject *object,guint property_id,
                                      GValue *value,GParamSpec *ps)
{
    WlBterProperties *obj=WL_BTER_PROPERTIES(object);
    switch(property_id) {
    case PROPERTY_TORRENT:
        g_value_set_pointer(value,obj->torrent);
        break;
    default:
        G_OBJECT_WARN_INVALID_PROPERTY_ID(object,property_id,ps);
    }
}

static void wl_bter_properties_setter(GObject *object,guint property_id,
                                      const GValue *value,GParamSpec *ps)
{
    WlBterProperties *obj=WL_BTER_PROPERTIES(object);
    switch(property_id) {
    case PROPERTY_TORRENT:
        obj->torrent=g_value_get_pointer (value);
        break;
    default:
        G_OBJECT_WARN_INVALID_PROPERTY_ID(object,property_id,ps);
    }
}

/**************************************************
 * PUBILC
 **************************************************/
GtkWidget *wl_bter_properties_new (void)
{
    GtkWidget *dialog=(GtkWidget *)g_object_new (WL_TYPE_BTER_PROPERTIES,NULL);

    return dialog;
}
GtkWidget *wl_bter_properties_new_with_torrent(tr_torrent *torrent)
{
    GtkWidget *dialog=(GtkWidget *)g_object_new (WL_TYPE_BTER_PROPERTIES,
                      "torrent",torrent,NULL);

    return dialog;
}

