/*
 * Copyright (C) 2014-2014 Wiky L(wiiiky@yeah.net)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * this file is generated by gobj(https://github.com/wiiiky/gobj)
 */

#include "wlbtermenu.h"


enum {
	WL_BTER_MENU_PROPERTY_BTER = 1,
};

G_DEFINE_TYPE(WlBterMenu, wl_bter_menu, GTK_TYPE_MENU);

static void wl_bter_menu_init(WlBterMenu * obj);
static void wl_bter_menu_finalize(GObject * obj);
static void wl_bter_menu_class_init(WlBterMenuClass * klass);
static void wl_bter_menu_getter(GObject * object, guint property_id,
								GValue * value, GParamSpec * ps);
static void wl_bter_menu_setter(GObject * object, guint property_id,
								const GValue * value, GParamSpec * ps);

static void wl_bter_menu_init(WlBterMenu * obj)
{
	GtkMenu *menu = GTK_MENU(obj);
	GtkWidget *properties =
		gtk_image_menu_item_new_from_stock(GTK_STOCK_PROPERTIES, NULL);
	gtk_widget_show(properties);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu), properties);

	obj->bter = NULL;
}

static void wl_bter_menu_finalize(GObject * obj)
{
}

static void wl_bter_menu_class_init(WlBterMenuClass * klass)
{
	GObjectClass *obj_class = G_OBJECT_CLASS(klass);
	obj_class->get_property = wl_bter_menu_getter;
	obj_class->set_property = wl_bter_menu_setter;
	obj_class->finalize = wl_bter_menu_finalize;

	GParamSpec *ps;
	ps = g_param_spec_pointer("bter",
							  "wlbter",
							  "WlBter",
							  G_PARAM_READABLE | G_PARAM_WRITABLE |
							  G_PARAM_CONSTRUCT_ONLY);
	g_object_class_install_property(obj_class, WL_BTER_MENU_PROPERTY_BTER,
									ps);
}

static void wl_bter_menu_getter(GObject * object, guint property_id,
								GValue * value, GParamSpec * ps)
{
	WlBterMenu *obj = WL_BTER_MENU(object);
	switch (property_id) {
	case WL_BTER_MENU_PROPERTY_BTER:
		g_value_set_pointer(value, obj->bter);
		break;
	default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID(object, property_id, ps);
	}
}

static void wl_bter_menu_setter(GObject * object, guint property_id,
								const GValue * value, GParamSpec * ps)
{
	WlBterMenu *obj = WL_BTER_MENU(object);
	switch (property_id) {
	case WL_BTER_MENU_PROPERTY_BTER:
		obj->bter = g_value_get_pointer(value);
		break;
	default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID(object, property_id, ps);
	}
}

/**************************************************
 * PUBILC
 **************************************************/
WlBterMenu *wl_bter_menu_new(WlBter * bter)
{
	g_return_val_if_fail(WL_IS_BTER(bter), NULL);
	WlBterMenu *menu =
		(WlBterMenu *) g_object_new(WL_TYPE_BTER_MENU, "bter", bter, NULL);
	wl_bter_set_popmenu(bter, GTK_WIDGET(menu));
	return menu;
}
