/*
 * Copyright (C) 2014-2014 Wiky L(wiiiky@yeah.net)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * this file is generated by gobj(https://github.com/wiiiky/gobj)
 */

#include "wlbtfilechooser.h"

G_DEFINE_TYPE(WlBtFileChooser, wl_bt_file_chooser, GTK_TYPE_DIALOG);

static void wl_bt_file_chooser_init(WlBtFileChooser *obj);
static void wl_bt_file_chooser_finalize(GObject *obj);
static void wl_bt_file_chooser_class_init(WlBtFileChooserClass *klass);
static void wl_bt_file_chooser_getter(GObject *object,guint property_id,
									GValue *value,GParamSpec *ps);
static void wl_bt_file_chooser_setter(GObject *object,guint property_id,
									const GValue *value,GParamSpec *ps);

static void wl_bt_file_chooser_init(WlBtFileChooser *obj)
{
}

static void wl_bt_file_chooser_finalize(GObject *obj)
{
}

static void wl_bt_file_chooser_class_init(WlBtFileChooserClass *klass)
{
	GObjectClass *obj_class=G_OBJECT_CLASS(klass);
	obj_class->get_property=wl_bt_file_chooser_getter;
	obj_class->set_property=wl_bt_file_chooser_setter;
	obj_class->finalize=wl_bt_file_chooser_finalize;

	GParamSpec *ps;
	/* properties */
}

static void wl_bt_file_chooser_getter(GObject *object,guint property_id,
									GValue *value,GParamSpec *ps)
{
	WlBtFileChooser *obj=WL_BT_FILE_CHOOSER(object);
	switch(property_id){
		default:
			G_OBJECT_WARN_INVALID_PROPERTY_ID(object,property_id,ps);
	}
}

static void wl_bt_file_chooser_setter(GObject *object,guint property_id,
								const GValue *value,GParamSpec *ps)
{
	WlBtFileChooser *obj=WL_BT_FILE_CHOOSER(object);
	switch(property_id){
		default:
			G_OBJECT_WARN_INVALID_PROPERTY_ID(object,property_id,ps);
	}
}
