/*
 * Copyright (C) 2014-2014 Wiky L(wiiiky@yeah.net)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * this file is generated by gobj(https://github.com/wiiiky/gobj)
 */

#include "wlbterproperties.h"

enum {
    PROPERTY_TORRENT=1,
};

G_DEFINE_TYPE(WlBterProperties, wl_bter_properties, GTK_TYPE_DIALOG);

static void wl_bter_properties_init(WlBterProperties *obj);
static void wl_bter_properties_finalize(GObject *obj);
static void wl_bter_properties_class_init(WlBterPropertiesClass *klass);
static void wl_bter_properties_getter(GObject *object,guint property_id,
                                      GValue *value,GParamSpec *ps);
static void wl_bter_properties_setter(GObject *object,guint property_id,
                                      const GValue *value,GParamSpec *ps);

static void onDialogResponse(GtkDialog *dialog,gint reponseId,gpointer data);
static gboolean onDialogDelete(GtkWidget *dialog,GdkEvent *event,gpointer data);

static void wl_bter_properties_init(WlBterProperties *obj)
{
    gtk_container_set_border_width (GTK_CONTAINER(obj),8);
    gtk_window_set_modal (GTK_WINDOW(obj),TRUE);
    gtk_window_set_default_size (GTK_WINDOW(obj),480,560);
    gtk_dialog_add_button (GTK_DIALOG(obj),"Close",GTK_RESPONSE_CLOSE);
    gtk_dialog_set_default_response (GTK_DIALOG(obj),GTK_RESPONSE_CLOSE);

    GtkWidget *box=gtk_dialog_get_content_area (GTK_DIALOG(obj));
    GtkWidget *notebook=gtk_notebook_new ();
    gtk_box_pack_start (GTK_BOX(box),notebook,TRUE,TRUE,0);


    GtkWidget *infoBox=gtk_box_new (GTK_ORIENTATION_VERTICAL,5);
    gtk_notebook_append_page (GTK_NOTEBOOK(notebook),infoBox,
                              gtk_label_new ("infomation"));

    obj->torrent=NULL;

    /* signals */
    g_signal_connect(G_OBJECT(obj),"response",
                     G_CALLBACK(onDialogResponse),NULL);
    g_signal_connect(G_OBJECT(obj),"delete-event",
                     G_CALLBACK(onDialogDelete),NULL);
}

static void wl_bter_properties_finalize(GObject *obj)
{
}

static void wl_bter_properties_class_init(WlBterPropertiesClass *klass)
{
    GObjectClass *objClass=G_OBJECT_CLASS(klass);
    objClass->get_property=wl_bter_properties_getter;
    objClass->set_property=wl_bter_properties_setter;
    objClass->finalize=wl_bter_properties_finalize;

    GParamSpec *ps;
    /* properties */
    ps=g_param_spec_pointer ("torrent",
                             "tr_torrent",
                             "Tr Torrent",
                             G_PARAM_READABLE|G_PARAM_WRITABLE|
                             G_PARAM_CONSTRUCT);
    g_object_class_install_property (objClass,PROPERTY_TORRENT,ps);
}

static void wl_bter_properties_getter(GObject *object,guint property_id,
                                      GValue *value,GParamSpec *ps)
{
    WlBterProperties *obj=WL_BTER_PROPERTIES(object);
    switch(property_id) {
    case PROPERTY_TORRENT:
        g_value_set_pointer(value,obj->torrent);
        break;
    default:
        G_OBJECT_WARN_INVALID_PROPERTY_ID(object,property_id,ps);
    }
}

static void wl_bter_properties_setter(GObject *object,guint property_id,
                                      const GValue *value,GParamSpec *ps)
{
    WlBterProperties *obj=WL_BTER_PROPERTIES(object);
    switch(property_id) {
    case PROPERTY_TORRENT:
        obj->torrent=g_value_get_pointer (value);
        break;
    default:
        G_OBJECT_WARN_INVALID_PROPERTY_ID(object,property_id,ps);
    }
}

static void onDialogResponse(GtkDialog *dialog,gint reponseId,gpointer data)
{
    gtk_widget_hide (GTK_WIDGET(dialog));
}

static gboolean onDialogDelete(GtkWidget *dialog,GdkEvent *event,gpointer data)
{
    gtk_dialog_response (GTK_DIALOG(dialog),GTK_RESPONSE_CLOSE);
    return TRUE;
}

/**************************************************
 * PUBILC
 **************************************************/
GtkWidget *wl_bter_properties_new (void)
{
    GtkWidget *dialog=(GtkWidget *)g_object_new (WL_TYPE_BTER_PROPERTIES,NULL);

    return dialog;
}
GtkWidget *wl_bter_properties_new_with_torrent(tr_torrent *torrent)
{
    GtkWidget *dialog=(GtkWidget *)g_object_new (WL_TYPE_BTER_PROPERTIES,
                      "torrent",torrent,NULL);

    return dialog;
}

void wl_bter_properties_set_torrent(WlBterProperties *dialog,tr_torrent *torrent)
{
    g_return_if_fail(WL_IS_BTER_PROPERTIES(dialog));
    g_object_set(G_OBJECT(dialog),"torrent",torrent,NULL);
}

