/*
 * Copyright (C) 2014-2014 Wiky L(wiiiky@yeah.net)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * this file is generated by gobj(https://github.com/wiiiky/gobj)
 */

#ifndef __WL_BT_FILE_CHOOSER_H__
#define __WL_BT_FILE_CHOOSER_H__

#include<gtk/gtk.h>
#include"libtransmission/transmission.h"


#ifndef PACKAGE_DATA_DIR
#define PACKAGE_DATA_DIR "./data"
#endif

#define UI_FILE PACKAGE_DATA_DIR "/torrent.ui"

G_BEGIN_DECLS
/* Macro for casting a pointer to a WlBtFileChooser or WlBtFileChooserClass pointer.
 * Macros for testing whether `object' or `klass' are of type WL_TYPE_BT_FILE_CHOOSER.
 */
#define WL_TYPE_BT_FILE_CHOOSER	(wl_bt_file_chooser_get_type())
#define WL_BT_FILE_CHOOSER(obj)	(G_TYPE_CHECK_INSTANCE_CAST ((obj), WL_TYPE_BT_FILE_CHOOSER, WlBtFileChooser))
#define WL_BT_FILE_CHOOSER_CLASS(klass)	(G_TYPE_CHECK_CLASS_CAST ((klass), WL_TYPE_BT_FILE_CHOOSER, WlBtFileChooserClass))
#define WL_IS_BT_FILE_CHOOSER(obj)	(G_TYPE_CHECK_INSTANCE_TYPE ((obj), WL_TYPE_BT_FILE_CHOOSER))
#define WL_IS_BT_FILE_CHOOSER_CLASS(klass)	(G_TYPE_CHECK_CLASS_TYPE ((klass), WL_TYPE_BT_FILE_CHOOSER))
#define WL_BT_FILE_CHOOSER_GET_CLASS(obj)	(G_TYPE_INSTANCE_GET_CLASS ((obj), WL_TYPE_BT_FILE_CHOOSER, WlBtFileChooserClass))
typedef struct _WlBtFileChooser WlBtFileChooser;
typedef struct _WlBtFileChooserClass WlBtFileChooserClass;


struct _WlBtFileChooser {
	GtkBuilder parent;
	/*Private */
	tr_torrent *torrent;
};

struct _WlBtFileChooserClass {
	GtkBuilderClass parent_class;
	/*Private */
};

GType wl_bt_file_chooser_get_type(void) G_GNUC_CONST;

/* Public */
WlBtFileChooser *wl_bt_file_chooser_new(tr_torrent * torrent);


G_END_DECLS
#endif
